# Generated by Django 3.0.1 on 2020-01-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=20000)),
                ('calligraphy', models.CharField(max_length=20000)),
                ('timeStamp', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=1000)),
            ],
        ),
    ]
